name: Release Package

on:
  push:
    tags:
      - "core-v*"
      - "react-v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - run: pnpm install --frozen-lockfile

      - name: Detect package
        id: detect
        run: |
          if [[ $GITHUB_REF == refs/tags/core-v* ]]; then
            echo "pkg=rendero-core" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/react-v* ]]; then
            echo "pkg=rendero-react" >> $GITHUB_OUTPUT
          fi

      - name: Run Lint
        run: pnpm --filter @vanekt/${{ steps.detect.outputs.pkg }} lint

      - name: Run Tests
        run: pnpm --filter @vanekt/${{ steps.detect.outputs.pkg }} test

      - name: Build package
        run: pnpm --filter @vanekt/${{ steps.detect.outputs.pkg }} build

      - name: Publish to npm
        run: pnpm --filter @vanekt/${{ steps.detect.outputs.pkg }} publish --provenance --access public --registry https://registry.npmjs.org/ --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
